export const ROUTE_PATHS = {
  root: '/',
  login: '/login',
  dashboard: '/dashboard',
  appointments: '/appointments',
  createAppointment: '/appointments/new',
  clients: '/clients',
  createClient: '/clients/new',
  services: '/services',
  createService: '/services/new',
  availability: '/availability',
  createAvailability: '/availability/new',
  profile: '/profile',
  settings: '/settings',
} as const
